export const GET_SENSOR_LIST_START = 'GET_SENSOR_LIST_START';
export const GET_SENSOR_LIST_SUCCESS = 'GET_SENSOR_LIST_SUCCESS';
export const GET_SENSOR_LIST_FAIL = 'GET_SENSOR_LIST_FAIL';
export const GET_PERIOD_SENSOR_VALUES_START = 'GET_PERIOD_SENSOR_VALUES_START';
export const GET_PERIOD_SENSOR_VALUES_SUCCESS = 'GET_PERIOD_SENSOR_VALUES_SUCCESS';
export const GET_PERIOD_SENSOR_VALUES_FAIL = 'GET_PERIOD_SENSOR_VALUES_FAIL';
